new
genome hg38
load s3://davelab-analysis-results/33391/AAC096_A_A32844/discowave/AAC096_A_A32844/discowave.AAC096_A_A32844.AAC096_A_A32844.discordant_reads.diff_chrom.bam index=s3://davelab-analysis-results/33391/AAC096_A_A32844/discowave/AAC096_A_A32844/discowave.AAC096_A_A32844.AAC096_A_A32844.discordant_reads.diff_chrom.bam.bai
snapshotDirectory /home/devang/Downloads/Rachel/33391
load gs://davelab_data/ref/human/hg38/capture_baits/twist/maskPAR/Twist_8MB_panel_with_ERCCs.maskPAR.bed
load gs://davelab_data/ref/naresh_sv/hg38_repeat_masker.sorted.bed
load gs://davelab_data/ref/naresh_sv/hg38_segmental_dups.sorted.bed
goto chr8:127790374-127790974 chr11:33210265-33210865
sort position
collapse
expand ref%2Fnaresh_sv%2Fhg38_repeat_masker.sorted.bed
expand ref%2Fnaresh_sv%2Fhg38_segmental_dups.sorted.bed
expand ref%2Fhuman%2Fhg38%2Fcapture_baits%2Ftwist%2FmaskPAR%2FTwist_8MB_panel_with_ERCCs.maskPAR.bed
collapse Gene
group MATE_CHROMOSOME
snapshot MYC_33391_chr8_127790674-chr11_33210565_split_group.png
new
genome hg38
load s3://davelab-analysis-results/33067/AAC098_A_A31980/discowave/AAC098_A_A31980/discowave.AAC098_A_A31980.AAC098_A_A31980.discordant_reads.diff_chrom.bam index=s3://davelab-analysis-results/33067/AAC098_A_A31980/discowave/AAC098_A_A31980/discowave.AAC098_A_A31980.AAC098_A_A31980.discordant_reads.diff_chrom.bam.bai
snapshotDirectory /home/devang/Downloads/Rachel/33067
load gs://davelab_data/ref/human/hg38/capture_baits/twist/maskPAR/Twist_8MB_panel_with_ERCCs.maskPAR.bed
load gs://davelab_data/ref/naresh_sv/hg38_repeat_masker.sorted.bed
load gs://davelab_data/ref/naresh_sv/hg38_segmental_dups.sorted.bed
goto chr10:68342830-68343430 chr18:62515494-62516094
sort position
collapse
expand ref%2Fnaresh_sv%2Fhg38_repeat_masker.sorted.bed
expand ref%2Fnaresh_sv%2Fhg38_segmental_dups.sorted.bed
expand ref%2Fhuman%2Fhg38%2Fcapture_baits%2Ftwist%2FmaskPAR%2FTwist_8MB_panel_with_ERCCs.maskPAR.bed
collapse Gene
group MATE_CHROMOSOME
snapshot BCL2_33067_chr10_68343130-chr18_62515794_split_group.png
new
genome hg38
load s3://davelab-analysis-results/33419/AAC107_A_A33195/discowave/AAC107_A_A33195/discowave.AAC107_A_A33195.AAC107_A_A33195.discordant_reads.diff_chrom.bam index=s3://davelab-analysis-results/33419/AAC107_A_A33195/discowave/AAC107_A_A33195/discowave.AAC107_A_A33195.AAC107_A_A33195.discordant_reads.diff_chrom.bam.bai
snapshotDirectory /home/devang/Downloads/Rachel/33419
load gs://davelab_data/ref/human/hg38/capture_baits/twist/maskPAR/Twist_8MB_panel_with_ERCCs.maskPAR.bed
load gs://davelab_data/ref/naresh_sv/hg38_repeat_masker.sorted.bed
load gs://davelab_data/ref/naresh_sv/hg38_segmental_dups.sorted.bed
goto chr3:187756291-187756891 chr4:85153005-85153605
sort position
collapse
expand ref%2Fnaresh_sv%2Fhg38_repeat_masker.sorted.bed
expand ref%2Fnaresh_sv%2Fhg38_segmental_dups.sorted.bed
expand ref%2Fhuman%2Fhg38%2Fcapture_baits%2Ftwist%2FmaskPAR%2FTwist_8MB_panel_with_ERCCs.maskPAR.bed
collapse Gene
group MATE_CHROMOSOME
snapshot BCL6_33419_chr3_187756591-chr4_85153305_split_group.png
new
genome hg38
load s3://davelab-analysis-results/33065/AAC113_A_A31978/discowave/AAC113_A_A31978/discowave.AAC113_A_A31978.AAC113_A_A31978.discordant_reads.diff_chrom.bam index=s3://davelab-analysis-results/33065/AAC113_A_A31978/discowave/AAC113_A_A31978/discowave.AAC113_A_A31978.AAC113_A_A31978.discordant_reads.diff_chrom.bam.bai
snapshotDirectory /home/devang/Downloads/Rachel/33065
load gs://davelab_data/ref/human/hg38/capture_baits/twist/maskPAR/Twist_8MB_panel_with_ERCCs.maskPAR.bed
load gs://davelab_data/ref/naresh_sv/hg38_repeat_masker.sorted.bed
load gs://davelab_data/ref/naresh_sv/hg38_segmental_dups.sorted.bed
goto chr6:125677015-125677615 chr8:128826913-128827513
sort position
collapse
expand ref%2Fnaresh_sv%2Fhg38_repeat_masker.sorted.bed
expand ref%2Fnaresh_sv%2Fhg38_segmental_dups.sorted.bed
expand ref%2Fhuman%2Fhg38%2Fcapture_baits%2Ftwist%2FmaskPAR%2FTwist_8MB_panel_with_ERCCs.maskPAR.bed
collapse Gene
group MATE_CHROMOSOME
snapshot MYC_33065_chr6_125677315-chr8_128827213_split_group.png
goto chr3:187785036-187785636 chr18:55325559-55326159
sort position
collapse
expand ref%2Fnaresh_sv%2Fhg38_repeat_masker.sorted.bed
expand ref%2Fnaresh_sv%2Fhg38_segmental_dups.sorted.bed
expand ref%2Fhuman%2Fhg38%2Fcapture_baits%2Ftwist%2FmaskPAR%2FTwist_8MB_panel_with_ERCCs.maskPAR.bed
collapse Gene
group MATE_CHROMOSOME
snapshot BCL6_33065_chr3_187785336-chr18_55325859_split_group.png
new
genome hg38
load s3://davelab-analysis-results/33394/AAC116_A_A32848/discowave/AAC116_A_A32848/discowave.AAC116_A_A32848.AAC116_A_A32848.discordant_reads.diff_chrom.bam index=s3://davelab-analysis-results/33394/AAC116_A_A32848/discowave/AAC116_A_A32848/discowave.AAC116_A_A32848.AAC116_A_A32848.discordant_reads.diff_chrom.bam.bai
snapshotDirectory /home/devang/Downloads/Rachel/33394
load gs://davelab_data/ref/human/hg38/capture_baits/twist/maskPAR/Twist_8MB_panel_with_ERCCs.maskPAR.bed
load gs://davelab_data/ref/naresh_sv/hg38_repeat_masker.sorted.bed
load gs://davelab_data/ref/naresh_sv/hg38_segmental_dups.sorted.bed
goto chr1:24672829-24673429 chr8:127087995-127088595
sort position
collapse
expand ref%2Fnaresh_sv%2Fhg38_repeat_masker.sorted.bed
expand ref%2Fnaresh_sv%2Fhg38_segmental_dups.sorted.bed
expand ref%2Fhuman%2Fhg38%2Fcapture_baits%2Ftwist%2FmaskPAR%2FTwist_8MB_panel_with_ERCCs.maskPAR.bed
collapse Gene
group MATE_CHROMOSOME
snapshot MYC_33394_chr1_24673129-chr8_127088295_split_group.png
new
genome hg38
load s3://davelab-analysis-results/33409/AAC117_A_A33175/discowave/AAC117_A_A33175/discowave.AAC117_A_A33175.AAC117_A_A33175.discordant_reads.diff_chrom.bam index=s3://davelab-analysis-results/33409/AAC117_A_A33175/discowave/AAC117_A_A33175/discowave.AAC117_A_A33175.AAC117_A_A33175.discordant_reads.diff_chrom.bam.bai
snapshotDirectory /home/devang/Downloads/Rachel/33409
load gs://davelab_data/ref/human/hg38/capture_baits/twist/maskPAR/Twist_8MB_panel_with_ERCCs.maskPAR.bed
load gs://davelab_data/ref/naresh_sv/hg38_repeat_masker.sorted.bed
load gs://davelab_data/ref/naresh_sv/hg38_segmental_dups.sorted.bed
goto chr5:133625811-133626411 chr8:129497480-129498080
sort position
collapse
expand ref%2Fnaresh_sv%2Fhg38_repeat_masker.sorted.bed
expand ref%2Fnaresh_sv%2Fhg38_segmental_dups.sorted.bed
expand ref%2Fhuman%2Fhg38%2Fcapture_baits%2Ftwist%2FmaskPAR%2FTwist_8MB_panel_with_ERCCs.maskPAR.bed
collapse Gene
group MATE_CHROMOSOME
snapshot MYC_33409_chr5_133626111-chr8_129497780_split_group.png
goto chr14:105888261-105888861 chr18:63125953-63126553
sort position
collapse
expand ref%2Fnaresh_sv%2Fhg38_repeat_masker.sorted.bed
expand ref%2Fnaresh_sv%2Fhg38_segmental_dups.sorted.bed
expand ref%2Fhuman%2Fhg38%2Fcapture_baits%2Ftwist%2FmaskPAR%2FTwist_8MB_panel_with_ERCCs.maskPAR.bed
collapse Gene
group MATE_CHROMOSOME
snapshot BCL2_33409_chr14_105888561-chr18_63126253_split_group.png
new
genome hg38
load s3://davelab-analysis-results/33411/AAC119_A_A33177/discowave/AAC119_A_A33177/discowave.AAC119_A_A33177.AAC119_A_A33177.discordant_reads.diff_chrom.bam index=s3://davelab-analysis-results/33411/AAC119_A_A33177/discowave/AAC119_A_A33177/discowave.AAC119_A_A33177.AAC119_A_A33177.discordant_reads.diff_chrom.bam.bai
snapshotDirectory /home/devang/Downloads/Rachel/33411
load gs://davelab_data/ref/human/hg38/capture_baits/twist/maskPAR/Twist_8MB_panel_with_ERCCs.maskPAR.bed
load gs://davelab_data/ref/naresh_sv/hg38_repeat_masker.sorted.bed
load gs://davelab_data/ref/naresh_sv/hg38_segmental_dups.sorted.bed
goto chr5:133625812-133626412 chr8:129497495-129498095
sort position
collapse
expand ref%2Fnaresh_sv%2Fhg38_repeat_masker.sorted.bed
expand ref%2Fnaresh_sv%2Fhg38_segmental_dups.sorted.bed
expand ref%2Fhuman%2Fhg38%2Fcapture_baits%2Ftwist%2FmaskPAR%2FTwist_8MB_panel_with_ERCCs.maskPAR.bed
collapse Gene
group MATE_CHROMOSOME
snapshot MYC_33411_chr5_133626112-chr8_129497795_split_group.png
