new
genome hg19
load /data/discowave.bam index=/data/discowave.bam.bai
#load s3://davelab-analysis-results/33391/AAC096_A_A32844/discowave/AAC096_A_A32844/discowave.AAC096_A_A32844.AAC096_A_A32844.discordant_reads.diff_chrom.bam index=s3://davelab-analysis-results/33391/AAC096_A_A32844/discowave/AAC096_A_A32844/discowave.AAC096_A_A32844.AAC096_A_A32844.discordant_reads.diff_chrom.bam.bai
goto chr2:3291-3991 chr3:10000
snapshotDirectory /data
snapshot test.png
exit
